// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWeVDS0yoJ6F8VKaXHkEqXBfl_rZZBBvM',
    appId: '1:944869478615:web:1344eba682a768d9d96092',
    messagingSenderId: '944869478615',
    projectId: 'letschat-app23',
    authDomain: 'letschat-app23.firebaseapp.com',
    storageBucket: 'letschat-app23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBESQ9sv5uL8jwryPihVeyjgFFHigFfwAc',
    appId: '1:944869478615:android:2e1da791dd971631d96092',
    messagingSenderId: '944869478615',
    projectId: 'letschat-app23',
    storageBucket: 'letschat-app23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXxiUoqXgYQCBeth64cLM0CAaB_r-VrS8',
    appId: '1:944869478615:ios:8f76eae835d1ed18d96092',
    messagingSenderId: '944869478615',
    projectId: 'letschat-app23',
    storageBucket: 'letschat-app23.appspot.com',
    iosBundleId: 'com.example.demoApplication',
  );
}
